# syntax=docker/dockerfile:1.4

FROM node:lts AS development

ENV PORT=3001

WORKDIR /app
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
RUN yarn install
COPY . /app

CMD [ "yarn", "start" ]
